# Generated by Django 4.1.2 on 2022-10-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='clue',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
